name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build & Publish
        run: ./gradlew build publish --stacktrace
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GITHUB_RELEASE: true
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/arrp-${{ github.event.release.tag_name }}.jar
          tag_name: ${{ github.event.release.tag_name }}
